### ISSUE TITLE
normalization question for whole genome

### ISSUE THREAD

**Issue by lpantano** [raerose01/deconstructSigs#1]
Hi,

this package seems great! thank u!

I have some whole genome seq that I wanted to try, but I am bit confused about whether I have to set on `tri.counts.method` to `genome` or not. I want them to compare to `signatures.nature2013` signature. 

any help will be great!

thanks

**Comment by raerose01** [comment]
Hi, 

Glad you think the package seems useful! 

According to the published notes about the original signatures.nature2013, they reflect absolute frequencies as would occur in whole-genome data, so to compare to WGS, you would not have to use the genome method. However if you did use the method, you should be sure to normalize the signatures input as well.

Hope that helps,

Rachel

**Comment by lpantano** [comment]
Thanks a lot! Good to know exactly when and how to normalized.

cheers!
