### ISSUE TITLE
The ESCA data

### ISSUE THREAD

**Issue by Rashesh7** [raerose01/deconstructSigs#11]
Hi,

I am working on implementing this tool in the pipeline and wanted to compare it with other tools available. 
I see you have used the TCGA-ESCA data in the paper, but the Signature predictions are not present in the Supplementary tables. 
Please let me know if they are present in any other file or if you could please provide me the table, so I can use that as a benchmark. (Just like other datasets are present in Additional File 6 in the paper)

**Comment by raerose01** [comment]
Hi, here's deconstructSigs run on the data provided in the ESCA Supplementary Table. The weights can be found in the files called *.weights. Hope that helps.

Rachel

[esca.signatures.RData.zip](https://github.com/raerose01/deconstructSigs/files/847552/esca.signatures.RData.zip)
