### ISSUE TITLE
problem with mut.to.sigs.input

### ISSUE THREAD

**Issue by juansearch** [raerose01/deconstructSigs#15]
Dear raerose01,
I am using deconstructSigs for the first time and having difficulty. I have a data frame of somatic mutations in the format: 
 sample.id   chr     pos ref alt
sample1 6  32157652   C   G
When I try to import this using mut.to.sigs.input I get an error

sig<-mut.to.sigs.input(ds,sample.id="sample.id",chr="chr",pos="pos",ref="ref",alt="alt",bsg=BSgenome.Hsapiens.UCSC.hg19)

Error in .local(x, ...) : 
  'start', 'end' and 'width' can only be specified when 'names' is either missing, a character vector/factor, a character-Rle, or a factor-Rle

Please help,
Juan

**Comment by raerose01** [comment]
Does it work when you try the example?

```
sigs.input = mut.to.sigs.input(mut.ref = sample.mut.ref, sample.id = "Sample",
chr = "chr", pos = "pos", ref = "ref", alt = "alt", bsg = 
BSgenome.Hsapiens.UCSC.hg19)
```

**Comment by juansearch** [comment]
There appears to be an issue with my input data, I think I have worked it out.
Thanks,

Juan L Rodríguez-Flores, PhD
Assistant Professor
Department of Genetic Medicine
Weill Cornell Medical College

Office: 1305 York Ave, 13th floor, room 1334, New York, NY 10021
Phone: (+1) 646-962-5553
Fax: (+1) 646-962-0220
Email: jur2014@med.cornell.edu<mailto:jur2014@med.cornell.edu>
Web: http://vivo.med.cornell.edu/display/cwid-jur2014
________________________________

**Comment by gilhornung** [comment]
Just as a reference:
I also encountered the same bug. For me, the problem was that the input data frame was actually a [tibble](https://tibble.tidyverse.org/) - the data frame used in the tidyverse.

**Comment by linhong-bgi** [comment]
Hi @juansearch 
I had the same problem, do you remember how to deal with input data.
