### ISSUE TITLE
non-default genomes

### ISSUE THREAD

**Issue by rsiddaway** [raerose01/deconstructSigs#16]
Thanks for the great package!

I'm trying to run on mouse data, and having trouble with it. I'm using 
`bsg = BSgenome.Mmusculus.UCSC.mm10` to provide a BSgenome object for `mut.to.sigs.input`, but I keep getting the following error:

> Error in as.character.default(<S4 object of class "BSgenome">) :
>   no method for coercing this S4 class to a vector

`BSgenome.Mmusculus.UCSC.mm10` is a `BSgenome ` object. I also tried for some human data to manually set `bsg = BSgenome.Hsapiens.UCSC.hg19`, but get the same error, regardless of whether I append `::Hsapiens` to the end of the object name. The function works perfectly if I use default bsg, but this should be the same thing. Is there something obvious that I'm missing here?

Thanks,
Rob

**Comment by csardas** [comment]
Seems the bug was fixed
There was a patch committed on 2016.Nov (after release 1.8.0 on CRAN)
https://github.com/raerose01/deconstructSigs/commit/02de348aca7a074cfc1604b83b246ff9f8522298

**Comment by rsiddaway** [comment]
Thanks for that, I re-installed direct from github and it worked fine.
Cheers,
Rob
