### ISSUE TITLE
mut.to.sigs.input Error in GrCH38

### ISSUE THREAD

**Issue by mgala81** [raerose01/deconstructSigs#19]
[test4.txt](https://github.com/raerose01/deconstructSigs/files/1095857/test4.txt)

Certain genomic profiles are generating the error:
Error in if (trimer %in% all.tri) { : argument is of length zero

I'm using the appropiate BSgenome object. I've attached a sample input file. I tried adding a check to see if trimer was not null prior, but that ended up creating a blank matrix.

**Comment by raerose01** [comment]
Hi, do you have an example of what's causing the error?

**Comment by mgala81** [comment]
Hi- I attached a file to the thread called test4.txt which the input. The second sample from TCGA (2 total) is causing the error.  The first sample when done alone creates no issue.

Best,

Manish
________________________________

**Comment by mgala81** [comment]
Here is the file again if not seen.
[test4.txt](https://github.com/raerose01/deconstructSigs/files/1095994/test4.txt)

**Comment by raerose01** [comment]
Ok, I think it should be fixed now. At least, that file ran for me. But you should re-install the package from the GitHub site. And if it still doesn't work, can you try changing the first column name to be "Sample" and let me know? Something odd was failing earlier.

**Comment by mgala81** [comment]
Many thanks, it works well now!
________________________________
