### ISSUE TITLE
Use with non-human genome

### ISSUE THREAD

**Issue by nriddiford** [raerose01/deconstructSigs#20]
Hi, 

It's not clear to me whether setting the `bsg` option to another genome in `mut.to.sigs.input()` (e.g. `mut.to.sigs.input(bsg=BSgenome.Dmelanogaster.UCSC.dm6) is sufficient to apply the correct normalisation in `whichSignatures(tri.counts.method = 'genome')`.

Your README says:

```
Included with the package are tri.counts.exome, which contains the trinucleotide counts for an exome and tri.counts.genome, which contains the trinucleotide counts for the hg19 genome
```

Does this change if we supply a different genome? Or will it always normalise to counts in hg19?

Thanks, 

Nick

**Comment by raerose01** [comment]
Hi Nick,

Currently the trinucleotide count files are only from hg19, so you would
need to calculate and provide the data frame containing scaling factor for
different genomes.

Rachel

**Comment by nriddiford** [comment]
Hi Rachel, 

Thanks for the reply. Would you be able to point me to the part of your code where these calculations are made? 

Best,

Nick

**Comment by raerose01** [comment]
Hi Nick,

Sure, that's in the following script:

https://github.com/raerose01/deconstructSigs/blob/master/R/normalize.data.R

Specifically in the getTriContextFraction section at line 123.

Rachel

**Comment by nriddiford** [comment]
Hi Rachel, 

Thanks for the reply. 

I've calculated the triniuc.counts in the genome in the same format as your `tri.counts.genome`, now can I just supply a this as a data frame to `whichSignatures` using the option `tri.counts.method`?. From the README it sounds like that that's the case: 

```
Finally, if tri.counts.method is set to a data frame present in the workspace, normalization is done by  
using that data frame as a scaling factor. The count data for each trinucleotide context is multiplied by  
the corresponding value given in the data frame.
```

Thanks, 

Nick

**Comment by raerose01** [comment]
Hi Nick,

The data frame supplied is used as a scaling factor, so you should take
1/(your.trinuc.counts) as input to whichSignatures.

Let me know if you have any other questions,

Rachel

**Comment by nriddiford** [comment]
OK so rather than this:

```
           x
AAA 10637628
AAC  4706682
AAG  4784766
AAT  7718698
```

I need to supply this:

```
           x
AAA 9.400592e-08
AAC  2.124639e-07
AAG  2.089966e-07
AAT  1.295555e-07
```

**Comment by raerose01** [comment]
Yup, that should do it.

**Comment by nriddiford** [comment]
Excellent - thanks for your help! 

Nick

**Comment by alejandro-jimenezsanchez** [comment]
Hi,

I am trying to use deconstructSigs with the mouse genome but I am getting an error when I do:
`Mmusculus <- getBSgenome(BSgenome.Mmusculus.UCSC.mm10, masked=FALSE)`
`sigs.input <- mut.to.sigs.input(mut.ref = my_input,
                                                     sample.id = "sample.id",
                                                     chr = "chr",
                                                     pos = "pos",
                                                     ref = "ref",
                                                     alt = "alt",
                                                     bsg = Mmusculus)`

Do you have an idea of why this may be?

Best,
Alejandro

**Comment by raerose01** [comment]
Hi Alejandro,

What's the error you're getting?

Thanks,

Rachel

**Comment by alejandro-jimenezsanchez** [comment]
Hi Rachel,

The error is:
 `Error in as.character.default(<S4 object of class "BSgenome">) : 
  no method for coercing this S4 class to a vector`

I don't get that error if I let bsg as default, but that uses hg19.

Thanks,
Alejandro

**Comment by raerose01** [comment]
Hi Alejandro,

I haven't encountered that error before. Do you have an example of a
mut.ref that fails?

Best,

Rachel

**Comment by alejandro-jimenezsanchez** [comment]
[edit]

I found that the names of some chromosomes were different and there was an error due to a bug in my script messing the position column, so the file below is wrong. Now deconstructSigs is running.

[original post]
This is the mut.ref:
[mafs_dS.txt](https://github.com/raerose01/deconstructSigs/files/1193763/mafs_dS.txt)

**Comment by alejandro-jimenezsanchez** [comment]
Hi Rachel,

I was wondering if you could try to run deconstructSig on that file using the mm10 mouse genome.

Thanks for help,
Alejandro

**Comment by raerose01** [comment]
Hi Alejandro,

I didn't get the same error you mentioned. Are you using the most
up-to-date version of the package from Github?

When I ran it, it only failed at row 2761 because the position doesn't
exist (chr10:161024159). Maybe double check that the file came from mm10?

Best,

Rachel

**Comment by alejandro-jimenezsanchez** [comment]
Hi Rachel,

I am using: `[Package deconstructSigs version 1.8.0 Index]`

Yes, I got that error too, I messed up the position file by mistake, the correct mut.ref file is this:
[mafs_dS.txt](https://github.com/raerose01/deconstructSigs/files/1205598/mafs_dS.txt)

Now, the function `mut.to.sigs.input` starts working, but then suddenly I get an R abort error, which I don't get with the example file.

This issue happens in my laptop, not sure what's the problem, but I'll try to run the program on a cluster.

Thanks for your help,
Alejandro

**Comment by fitbio** [comment]
Hi @alejandro-jimenezsanchez ,
In case of mouse genome, do we have same trinucleotide context as we see in Human hg19 genome?

**Comment by nriddiford** [comment]
You should be able to use [this function](https://github.com/nriddiford/mutationProfiles/blob/master/R/triCount.R) to calculate Trinuc. This returns a dataframe that you can use as the scaling factor for `whichSignatures`

**Comment by fitbio** [comment]
Thank you @nriddiford . But what if my mouse samples are whole exome? How can I calculate to get the trinucleoide frequency of different organisms? Do we have a tool?

**Comment by mozack** [comment]
> OK so rather than this:
> 
> ```
>            x
> AAA 10637628
> AAC  4706682
> AAG  4784766
> AAT  7718698
> ```
> I need to supply this:
> 
> ```
>            x
> AAA 9.400592e-08
> AAC  2.124639e-07
> AAG  2.089966e-07
> AAT  1.295555e-07
> ```

I am not sure this example is correct.  The tri-nucleotide sequences specified here are not present in the supplied tri.counts.genome data frame.  I suspect the counts for these should be added to their reverse complement sequence instead?

Also, do we know what exact hg19 fasta file was used to compute the supplied counts?  Are ambiguous IUPAC codes used or discarded?
