### ISSUE TITLE
Many Samples in my Maf files

### ISSUE THREAD

**Issue by AteeqMKhaliq** [raerose01/deconstructSigs#23]
Hi, I have around 90 Samples (taken from same tissues from different patients) in my .maf files, how should i be determining the signatures contributing to these 90 samples at a go? Its very difficult to provide sample.id every time. It would be really helpful if you can please help me in this case

For example:

sample_1 = whichSignatures(tumor.ref = sigs.input, 
                           signatures.ref = signatures.nature2013, 
                           **sample.id = 1,** 
                           contexts.needed = TRUE,
                           tri.counts.method = 'default')

 Should i manually change this every time and generate a graph or can i run these 90 samples together and generate graph at once? Its very confusing to run manually every sample.Please help.

Thanks a ton,
Zac

**Comment by raerose01** [comment]
Hi Zac,

I'd use something like lapply here. It'll give you the output for each sample in a list. 

So if you want to run the package on the first three example samples given it'd go something like this:

```
all_out <- lapply(rownames(randomly.generated.tumors)[1:3], FUN = function(x) whichSignatures(tumor.ref = randomly.generated.tumors, sample.id = x))
plotSignatures(all_out[[1]])
```

Hope that helps,

Rachel

**Comment by AteeqMKhaliq** [comment]
Thanks a Lot this helped, i am able to run the code.
Can we get the txt files, so that i can save for future reference. 
Currently i can save only Graphs

**Comment by raerose01** [comment]
That would be in the "weights" output.
`all_out[[1]]['weights']`
