### ISSUE TITLE
"Check ref bases -- not all match context" warning message

### ISSUE THREAD

**Issue by stevekm** [raerose01/deconstructSigs#26]
I was testing out this package with a public dataset as per [this script here](https://github.com/stevekm/Bioinformatics/blob/639a5ca5bde5cefc6d217713a654303457df70aa/mutational_signatures-deconstructSigs/demo.R), and got this error message:

```
Warning message:
    In mut.to.sigs.input(mut.ref = ccle, sample.id = "Tumor_Sample_Barcode",  :
                             Check ref bases -- not all match context:
                             22RV1_PROSTATE:chrM:9477:G:A, 22RV1_PROSTATE:chrM:14323:G:A, 253JBV_URINARY_TRACT:chrM:10589:G:A, 253JBV_URINARY_TRACT:chrM:13768:T:C, AML193_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:12720:A:G, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:6179:G:A, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:8684:C:T, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:14470:T:C, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:15148:G:A, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:15355:G:A, AMO1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:15487:A:T, BICR31_UPPER_AERODIGESTIVE_TRACT:chrM:14793:A:G, BICR31_UPPER_AERODIGESTIVE_TRACT:chrM:15218:A:G, BICR56_UPPER_AERODIGESTIVE_TRACT:chrM:8697:G:A, BICR56_UPPER_AERODIGESTIVE_TRACT:chrM:13928:G:C, BICR56_UPPER_AERODIGESTIVE_TRACT:chrM:14905:G:A, BICR6_UPPER_AERODIGESTIVE_TRACT:chrM:6365:T:C, BL41_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:11251:A:G, BL41_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE:chrM:12612:A:G, BL41_HAEMATOPOIETIC_AND_LY [... truncated]
```

I found the origin of this error message in the package source code [here](https://github.com/raerose01/deconstructSigs/blob/9bbaf15387e1a6221b4437523d12dd950eea80e1/R/mut.to.sigs.input.R#L103), however I am not clear on the significance of it. What exactly does this mean? And is there a way I can clean the data to avoid the issue? Thanks.

**Comment by raerose01** [comment]
That means that there are positions that do not match the reference base when it's being looked up in the BSgenome object. So for instance chrM:9477 is not a "G". The default in deconstructSigs is hg19, where it looks like that position is an "A" -- are you using hg38?

**Comment by flower1996** [comment]
I got the same problem when I used this package for my dataset, and the error message was
`Warning message:
In mut.to.sigs.input(mut.ref = snvs_xy, sample.id = "Tumor_Sample_Barcode",  :
  Check ref bases -- not all match context:
  caixiaoyang:chr1:1197893:C:A, caixiaoyang:chr1:16723988:A:C, caixiaoyang:chr3:52225629:C:A, caixiaoyang:chr3:119635504:C:T, caixiaoyang:chr4:3893510:A:G, caixiaoyang:chr4:131976071:G:A, caixiaoyang:chr5:77210864:C:T, caixiaoyang:chr6:34792177:G:A, caixiaoyang:chr7:56804306:C:T, caixiaoyang:chr7:143268853:A:T, caixiaoyang:chr8:144509304:G:A, caixiaoyang:chr9:62799226:A:G: [... truncated]`
The reference genome of mutation was hg38. And the BSgenome that I used was hg38, too.
Is there other Ideas what is going on? Or how can I avoid the issue? 
Thanks.

**Comment by raerose01** [comment]
Have you checked those on [UCSC Genome Browser](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr4%3A3893510%2D3893510&hgsid=780650377_mraXkFlFMwYZLzBWyJsly5e5HCkM) or similar? From what I looked up, it doesn't seem your reference base matches what's expected. For instance chr1:1197893:C is a T not a C.

**Comment by flower1996** [comment]
I have found the reason for this problem. There is no problem with raw mutation file, but I get some errors when using R to read the mutation file .maf.
Thanks for your help!
