### ISSUE TITLE
issue with BSgenome.Hsapiens.UCSC.hg38 in mut.to.sigs.input function

### ISSUE THREAD

**Issue by Puputnik** [raerose01/deconstructSigs#27]
Hello.
I'm running the following command:

sigs.input = mut.to.sigs.input(mut.ref = "/path/to/myfile.txt", sample.id = "Sample", chr = "chr", pos = "pos", ref = "ref", alt = "alt", bsg = BSgenome.Hsapiens.UCSC.hg38)

it gives me the following error: 
Error in as.character.default(<S4 object of class "BSgenome">) : 
  no method for coercing this S4 class to a vector

any suggestion?

Thank you very much for your work!

**Comment by Puputnik** [comment]
by the way, i forgot to say:
I've tried launching it without specifying the genome, and it seems to work (obviously it gives me some compatibility errors because my data are made with hg38, and if you don't specify the bsg field it uses hg19 by default), one strange thing is that if I try to specify the genome using  bsg = BSgenome.Hsapiens.UCSC.hg19 it gives me the same error as with hg38, and this doesn't really make sense to me.

Thanks again!

**Comment by raerose01** [comment]
Hi, I think a similar error was seen before.

Does re-installing as suggested in this thread fix the issue?

https://github.com/raerose01/deconstructSigs/issues/16

**Comment by lachlansimpson** [comment]
I've just found this error as well, in R 3.5.1 running on CentOS 7.5. BSgenome.Hsapiens.UCSC.hg38 wasn't even installed this AM - this was the first install. Immediately hit this error.

**Comment by lachlansimpson** [comment]
Installing from github seems to be the solution.
```
> library("devtools")
> install_github("raerose01/deconstructSigs")

```
