### ISSUE TITLE
question about the tri.count.method

### ISSUE THREAD

**Issue by MariaCartolano** [raerose01/deconstructSigs#28]
Hello,

would it be possible to describe how  the observed frequencies in the genome were counted? 

e.g 
stepwise window with a step of 3 and the start being equal to the first nucleotide of the chromosome 

count all possible triplets in a sequence: given a string , the triplets would be count from position 1-3,2-4,3-5 and so on....

I am struggling to think what is the best way. Thank you!

**Comment by raerose01** [comment]
The sliding window approach is the one used (so the second of your
suggestions) to account for each of the possible trinucleotide context
positions.

Rachel
