### ISSUE TITLE
Error in validObject(.Object) :    invalid class “DNAStringSet” object: undefined class for slot "elementMetadata" ("DataTableORNULL")

### ISSUE THREAD

**Issue by fjptwenger** [raerose01/deconstructSigs#29]
> head(d)
     Sample  chr    pos ref alt
1 SRR630583 chr1 735141   A   T
2 SRR630583 chr1 786021   A   T
3 SRR630583 chr1 794397   C   A
4 SRR630583 chr1 813831   A   T
5 SRR630583 chr1 848467   C   T
6 SRR630583 chr1 920860   A   G

sigs.input <- mut.to.sigs.input(mut.ref = d,sample.id="Sample",chr = "chr",  pos = "pos", ref = "ref",  alt = "alt")

####error
> sigs.input <- mut.to.sigs.input(mut.ref = d,sample.id="Sample",chr = "chr",  pos = "pos", ref = "ref",  alt = "alt")
Error in validObject(.Object) : 
  invalid class “DNAStringSet” object: undefined class for slot "elementMetadata" ("DataTableORNULL")

why this error happend?

**Comment by raerose01** [comment]
I can't say for sure based on what you have copied, but it's probably an incorrect data structure for _d_.
