### ISSUE TITLE
Possible to save `plotSignatures` object and print later?

### ISSUE THREAD

**Issue by stevekm** [raerose01/deconstructSigs#32]
If I run 

```
p <- plotSignatures(signatures, sub = 'signatures.cosmic')
```

The plot outputs to the graphics device, and `p` becomes `NULL` with warnings:

```
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cin" cannot be set
2: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cra" cannot be set
3: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "csi" cannot be set
4: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cxy" cannot be set
5: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "din" cannot be set
6: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "page" cannot be set
7: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cin" cannot be set
8: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cra" cannot be set
9: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "csi" cannot be set
10: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "cxy" cannot be set
11: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "din" cannot be set
12: In doTryCatch(return(expr), name, parentenv, handler) :
  graphical parameter "page" cannot be set
```

I want to be able to render the plot later, in a different location, potentially on a different system that does not have `deconstructSigs` installed. Passing around a pre-rendered PDF or PNG output is not desirable since it wont scale to fit the final location for rendering. Is there a way to do this?

**Comment by jgarces02** [comment]
Hi @stevekm. I recently had this problem and I found this (maybe provisional?) solution in [stackoverflow](https://stackoverflow.com/questions/29583849/save-a-plot-in-an-object):
```
p <- recordPlot()
plotSignatures(test.1)
p # to redraw
```
Nevertheless, your warnings messages are kept... only partially solved.

I hope this helps you. Regards.

**Comment by douym** [comment]
have the same problem here. Able to generate the figure but fail to print the titles and the weights on the figure.

**Comment by raerose01** [comment]
Do you mean the same error as this one?
https://github.com/raerose01/deconstructSigs/issues/52
That one should be fixed in the latest version from GitHub.

**Comment by douym** [comment]
Yes, that solves the problem. Thanks very much!
