### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by ZackDC** [raerose01/deconstructSigs#33]
Hi,
I want to use deconstructSigs to analyze the mutation signature of lung cancer patients with their whole exome sequencing data.
I run the command following the instruction in the page "https://github.com/raerose01/deconstructSigs".

After I loaded the data, 
(str(dat4)
'data.frame': 9623 obs. of  5 variables:
 $ X  : int  13 13 13 13 13 13 13 13 13 13 ...
 $ Chr: chr  "chr1" "chr1" "chr1" "chr1" ...
 $ End: int  2461397 2461418 2461421 3328849 3328852 3328858 3328861 3328873 3328876 3328889 ...
 $ Ref: chr  "G" "G" "G" "C" ...
 $ Alt: chr  "A" "C" "A" "T" ...)

 I run 
> sigs.input <- mut.to.sigs.input(mut.ref = dat4,
+                                sample.id = "X",
+                                    chr = "Chr",
+                                    pos = "End",
+                                    ref = "Ref",
+                                    alt = "Alt")
I got this:
Error in `[<-`(`*tmp*`, i, trimer, value = 21L) : subscript out of bounds
What is the mean of "subscript out of bounds"?
Can you tell me what is wrong with it?
Thank you!
Zack

**Comment by raerose01** [comment]
Hi Zack,
It's hard to guess without being able to re-create the error.
It sounds like one of your ref or alt sequences may not be correct. Alternatively, could you try making your sampleID column a string rather than int? 
If that doesn't work, can you send me a sample file that generates the error and I'll have a look.
Thanks,
Rachel

**Comment by ZackDC** [comment]
Hi Rachel,

Thank you very much for the reply!

I still can not find what is wrong with the ref or alt sequences.

The attachment is my data.

Thank you!

Warm wishes!

Zack

________________________________
发件人: raerose01 <notifications@github.com>
发送时间: 2018年6月5日 4:28:50
收件人: raerose01/deconstructSigs
抄送: Wei Yin; Author
主题: Re: [raerose01/deconstructSigs] subscript out of bounds (#33)


Hi Zack,
It's hard to guess without being able to re-create the error.
It sounds like one of your ref or alt sequences may not be correct. Alternatively, could you try making your sampleID column a string rather than int?
If that doesn't work, can you send me a sample file that generates the error and I'll have a look.
Thanks,
Rachel

―

**Comment by raerose01** [comment]
Hi Zack,

The following code works for me. You have to make the sampleID column something other than an int.

```
test <- read.csv(yourFile)
test$X <- as.character(test$X)
input <- mut.to.sigs.input(test, sample.id = 'X', chr = 'Chr', pos = 'End', ref = 'Ref', alt = 'Alt')
```

Best,

Rachel

**Comment by ZackDC** [comment]
Hi Rachel,

Thank you very much for the great help!

Warm wishes!

Zack

________________________________
发件人: raerose01 <notifications@github.com>
发送时间: 2018年6月5日 9:29:19
收件人: raerose01/deconstructSigs
抄送: Wei Yin; Author
主题: Re: [raerose01/deconstructSigs] subscript out of bounds (#33)


Hi Zack,

The following code works for me. You have to make the sampleID column something other than an int.

test <- read.csv(yourFile)
test$X <- as.character(test$X)
input <- mut.to.sigs.input(test, sample.id = 'X', chr = 'Chr', pos = 'End', ref = 'Ref', alt = 'Alt')

Best,

Rachel

―
