### ISSUE TITLE
Tri nucleoide frequency for exome data

### ISSUE THREAD

**Issue by fitbio** [raerose01/deconstructSigs#37]
I saw the option of using triFreq function that counts the number of times each triunucleotide is found in a supplied genome in genome level.  
But How to generate counts of every trinucleotide frequency in exome-level?

**Comment by raerose01** [comment]
Hi, just a heads up, that's not a deconstructSigs function. 

Looks like it came from here:
https://github.com/nriddiford/mutationProfiles/blob/master/R/triCount.R

So you may want to contact them with your question.

**Comment by fitbio** [comment]
Thank you. But can you please tell how did you generate tri.counts.exome data? I want to generate tri.counts.exome data for mouse samples which are also exomes. It would be helpful if you can provide me an idea

**Comment by raerose01** [comment]
I used a .bed file that corresponded to our exome sequencing run and the getSeq function here: https://www.rdocumentation.org/packages/Biostrings/versions/2.40.2/topics/getSeq. Then I extracted the correct positions and went through counting each trinucleotide context.

**Comment by fitbio** [comment]
Thank you. Here is what I did so far. I had my bed file imported.
v20130108.exome.targets<-`20130108.exome.targets`

exons_Granges<-GRanges(seqnames = v20130108.exome.targets$V1,IRanges(start = v20130108.exome.targets$V2,end=v20130108.exome.targets$V3))

Then using getSeq function to extract sequences of my exonic regions.

exonic_sequences<-getSeq(BSgenome.Hsapiens.UCSC.hg19,exons_Granges)

Then calculating trinuclotide frequency of exonic sequences.
trifreq_exons<-trinucleotideFrequency(exonic_sequences)
colSums(trifreq_exons)

But when I compared the values of your data (tri.counts.exome) with my results, my results seems to have higher values. For eg(ACA=784679)  whereas in your data, it was ACA=1749730. 

I had my bed file of chromosomes from 1-22 and X,Y.

I just need a help if you can suggest me in changing any of my steps. Thanks a lot :)
