### ISSUE TITLE
mut.to.sigs.input function does not work even on sample data

### ISSUE THREAD

**Issue by mkkuhner** [raerose01/deconstructSigs#38]
When I run mut.to.sigs.input either on my own data or on the provided data, I get errors similar to the following:

Error in `[.data.frame`(mut, , sample.id) : undefined columns selected

It does not matter whether I use the default genome or specify another one.  Colleagues who use the program regularly tell me that they simply don't use mut.to.sigs.input as it is perceived to be broken....

**Comment by messersc** [comment]
Hi @mkkuhner,

I am not affiliated with the authors of this package, but until they get back to you, maybe I can help with your problem. In our hands, the function `mut.to.sigs.input` works fine once you set everything up correctly. It is true that some pitfalls could be better documented. 

Here we go:

## Create the tsv from vcf
```
bcftools query \
    -f "$SAMPLE\t%CHROM\t%POS\t%REF\t%ALT\n" \
    -s $SAMPLE \
    input.vcf \
> output.tsv
```

## Use R and run the analysis

```
library(tidyverse)
library(deconstructSigs)

mutsigtable <- read_delim("output.tsv",
"\t", escape_double = FALSE, col_names = FALSE,
col_types = cols(X2 = col_character()),
trim_ws = TRUE)

colnames(mutsigtable) = c("Sample", "chr", "pos", "ref", "alt")

m = as.data.frame(mutsigtable)
m$chr = as.factor(m$chr)

sigs.input = mut.to.sigs.input(mut.ref = m)
                               #bsg = BSgenome.Hsapiens.UCSC.hg38::Hsapiens)

output.sigs = whichSignatures(tumor.ref = sigs.input,
                              #signatures.ref = signatures.nature2013,
                              signatures.ref = signatures.cosmic,
                              contexts.needed = TRUE,
                              #tri.counts.method = "exome2genome")
                              tri.counts.method = "default")

sigs = data.frame(colnames(output.sigs$weights), t(output.sigs$weights))
plotSignatures(output.sigs)
```

I think setting the `chr` column to factor was important!

hope it helps,
Clemens

PS. If this does not solve your problem, please provide more information so somebody can help you.
For example, the outputs of `sessionInfo()`, `head(df)` and `str(df)` if df is your data frame would help diagnose the problem.

**Comment by mkkuhner** [comment]
Hi Clemens, thanks for your help!  I have tracked my problem down to an error with column headers, probably due to my misreading the documentation.  I have mut.to.sigs.input working now.  Interestingly, the as.factor() does not seem to be necessary, though it does no harm either.

**Comment by mkkuhner** [comment]
Thank you!  Using your code as an idea source I was eventually able to
figure out my problem.  I really appreciate the help.

Mary Kuhner mkkuhner@uw.edu
