### ISSUE TITLE
Weights assigned to each signature do not always add up to 1

### ISSUE THREAD

**Issue by blecuacp** [raerose01/deconstructSigs#4]
Dear DecosntructSigs developers,

I recently used your software. While everything went smoothly, I noticed that, even in the examples you provide, the probabilities/weights assigned to each signature, using either nature or cosmic references, DO NOT always add up to 1. Why is that? Does that mean that a set of SNVs are not explained by any of the signatures?

I would highly appreciate your input.

Regards,

Pedro
Sloan Kettering Institute

**Comment by raerose01** [comment]
Hi Pedro,

In the [deconstructSigs paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0893-4) we explain that any signature with a weight < 6% is excluded. We also go through the analysis that allowed us to arrive at this 6% threshold. However, the cutoff value can be changed in the whichSignatures() function using the "signature.cutoff" parameter. 

In any case, in R, if you enter:

`sum(example.output[['weights']]) + example.output[['unknown']]
`

the answer will be 1.

Hope this clarifies things.

Rachel
