### ISSUE TITLE
signature matrix for new Alexandrov SBS signatures?

### ISSUE THREAD

**Issue by emham** [raerose01/deconstructSigs#50]
Hi, 

Is there a signature matrix for the expanded signature set detailed here? https://www.biorxiv.org/content/biorxiv/early/2018/05/15/322859.full.pdf

Thanks,
Emily

**Comment by Rashesh7** [comment]
Hi,

I was also wondering the same and is there a plan to support the Double base pair and Insertion/Deletion signatures from the same paper that @emham mentioned above. 

Thanks,
Rashesh

**Comment by niavarani** [comment]
Hi,
You can find the new SBS, DBS, and ID profiles as determined by SigProfiler from the following link:
https://www.synapse.org/#!Synapse:syn12009743
However, I am not sure how to change to this new signature while using the deconstructSigs R package.
Appreciate your kind assistance.
Ahmadreza

**Comment by sigven** [comment]
FYI: I asked a similar question wrt the MutationalPatterns package, thread here:
https://github.com/UMCUGenetics/MutationalPatterns/issues/29

best,
Sigve

**Comment by raerose01** [comment]
I have added the updated SBS signature matrices (from https://www.synapse.org/#!Synapse:syn12009743). I will look into modifying the whichSignatures function to include the DBS, and ID profiles as well.

**Comment by Rashesh7** [comment]
Hi @raerose01,

For DBS and ID, will you be also adding similar 'exome2genome' normalization function? 

Thank you!.

**Comment by Sumithrasank** [comment]
How can I call the Alexandrov SBS signatures in signatures.ref? i.e is there a preloaded file for this that comes with the package?

**Comment by raerose01** [comment]
Yes, if you download from Github, all files can be found in the data/ directory. They will be called something like "signatures.exome.cosmic.v3.may2019".

**Comment by Dagsbio** [comment]
If using exome data, should we use this new matrix: 

"signatures.dbs.cosmic.v3.may2019signatures.exome.cosmic.v3.may2019" ? 

Do we also have to set tri.counts.method to "exome2genome" ? 

Plus, can't we use at once a matrix containing both SBS and DBS? 

Thank you!
