### ISSUE TITLE
"signature weights" no longer displayed in graphics

### ISSUE THREAD

**Issue by spete021** [raerose01/deconstructSigs#52]
I have encountered two problems while using DeconstructSigs.
I have used DeconstructSigs a while ago and everthing worked fine, but lately I have the problem, that the title of the graph and weights  of the different signatures are no longer displayed in the graphics (after running plotSignatures). Additionally, in some cases "makepie() fails and shows a white pie called "1".

Does anyone have an idea how I can resolve these problems?

Thanks

**Comment by raerose01** [comment]
The first issue appears to be an update to the R barplot() function. I am trying to figure out how to fix it without breaking the function for anyone with older versions of R, but in the meantime, you can add "ann=TRUE" to lines 79, 86, and 93 in the plotSignatures() script. 

`graphics::barplot(tumor_plotting$fraction, names.arg = tumor_plotting$full_context, cex.names = 0.7, las = 2, col = factor(tumor_plotting$mutation), ylim = c(0, y_limit), border = NA, space = 0.3, main = top.title, ylab = 'fraction', add = TRUE, ann = TRUE)
`

Will look into the second issue.

**Comment by spete021** [comment]
Thank you very much for your help!

**Comment by raerose01** [comment]
Hi, I think I have fixed both issues. Let me know if it still doesn't work!

**Comment by DarioS** [comment]
I also had this problem, but installed deconstructSigs from GitHub and there is no longer a problem. I don't think it's bad to force users to upgrade R to the latest version. It would have many other improvements and fixes.
