### ISSUE TITLE
New COSMIC signatures (v3)

### ISSUE THREAD

**Issue by rahulk87** [raerose01/deconstructSigs#56]
Is there a way to run deconstructSigs for new COSMIC signatures (V3)?

**Comment by raerose01** [comment]
Yes, they are available in the most up-to-date package version.

https://github.com/raerose01/deconstructSigs/issues/50#issuecomment-534925824

**Comment by rahulk87** [comment]
I ran 1.9.0 version, it's giving me signature 1-30 (v2). 

I want to calculate the new signatures SBS1-85 (https://cancer.sanger.ac.uk/cosmic/signatures/SBS/).

**Comment by raerose01** [comment]
Yes, that's the "signatures.exome.cosmic.v3.may2019" file in version 1.9.0.

**Comment by rahulk87** [comment]
Thanks!!
