### ISSUE TITLE
Doubt when using updated signature matrices

### ISSUE THREAD

**Issue by Dagsbio** [raerose01/deconstructSigs#58]
If using exome data, should we use this new matrix:

"signatures.dbs.cosmic.v3.may2019signatures.exome.cosmic.v3.may2019" ?

Do we also have to set tri.counts.method to "exome2genome" ?

Plus, can't we use at once a matrix containing both SBS and DBS?

Thank you!

**Comment by raerose01** [comment]
Yes, if you want to use the most recent COSMIC release of the signatures you should use "signatures.exome.cosmic.v3.may2019". According to them, it was extracted from exome data only, so if you are also using exome data, "default" normalization should be fine.

And no, right now you would have to perform the SBS and DBS analyses separately.
