### ISSUE TITLE
mut.to.sigs.input for DBS

### ISSUE THREAD

**Issue by darwinchangz** [raerose01/deconstructSigs#59]
I'm attempting to create signature weights for DBS. When using the option (sig.type="DBS") I get an error saying that sig.type is an unused argument.

I installed deconstructSigs from the R package, not from github.

Is there something that I did wrong? When running this on only SBS, without the sig.type option, I get the correct output (at least it completes and I get weights) I also don't see any documentation on how else to differentiate SBS from DBS

R version 3.6
deconstructSigs_1.8.0

**Comment by raerose01** [comment]
The package version that includes DBS signatures only exists on GitHub. You can install it with:
`devtools::install_github("raerose01/deconstructSigs")`
