### ISSUE TITLE
hg38 support

### ISSUE THREAD

**Issue by LeonardJ09** [raerose01/deconstructSigs#6]
Hi there!

I am attempting to use your R tool to analyze some VCF files, and deconstruct the signatures within them. I am using HG38 as a reference, and when I change bsg to be BSgenome.Hsapiens.UCSC.hg38 i get the error "undefined columns selected". this is while running mut.to.sigs.input 

Is there support for hg38? I have been trying to find a workaround, but having the reference be tied up in the BSgenome library its hard to dev

**Comment by raerose01** [comment]
Hey, 

I have tried to recreate your error, but don't seem to get an error message. Could you send me an example of what you've run that fails?

Thanks,

Rachel

**Comment by LeonardJ09** [comment]
Figured it out this morning! I simply changed my column headers to match your example exactly and it worked. R was spitting out a column header error that I thought was coming from the hg38 reference, however after digging in your code found the error, and simply complied to your naming structure :)
