### ISSUE TITLE
Update to Mutational Signatures (v3.1 - June 2020)

### ISSUE THREAD

**Issue by kvaldez** [raerose01/deconstructSigs#66]
Hello!

The mutational signatures were updated this past June, can you provide these to download in the /data directory please?  I attached signatures that I downloaded for v3.1 from here: https://cancer.sanger.ac.uk/cosmic/signatures/SBS/index.tt. 

[COSMIC_Mutational_Signatures_v3.1.xlsx](https://github.com/raerose01/deconstructSigs/files/5036890/COSMIC_Mutational_Signatures_v3.1.xlsx)

Can I create this data myself by replacing this nomenclature:
C>A | ACA

With this?
A[C>A]A

Or is there more to it?

Thanks,
Kristin

**Comment by raerose01** [comment]
Hi Kristin,

Sure, it should be fine to replace the new signatures nomenclature with "A[C>A]A" style. Let me know if it causes any error though!

Rachel
