### ISSUE TITLE
Was blacklist used to create tri.count.genome?

### ISSUE THREAD

**Issue by yasunorikogure** [raerose01/deconstructSigs#69]
Hi there,

Do you know any blacklist was used before calculating tri.counts.genome (or tri.counts.exome)?
I found the count was different from other tools' corresponding data.

Thanks!

**Comment by raerose01** [comment]
Hi, no blacklist was used. Though for what it's worth, I think in the most recent release of COSMIC signatures, it's best to use default normalization.

**Comment by yasunorikogure** [comment]
I understand. Thank you for your comment.
