### ISSUE TITLE
Please release v1.9.0 for automated installations

### ISSUE THREAD

**Issue by naumenko-sa** [raerose01/deconstructSigs#71]
Hello Rachel @raerose01 !

Thanks for maintaining deconstructSigs!
Could you please make a release of the latest code under v1.9.0?

Automated installations via bioconda are getting the v1.8.0 version, 
https://anaconda.org/bioconda/r-deconstructsigs/files
https://anaconda.org/bioconda/r-deconstructsigs
https://cran.r-project.org/web/packages/deconstructSigs/index.html

and it breaks
the latest PureCN: https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/Quick.html

Making a release should fix it!

Sergey

**Comment by raerose01** [comment]
Hi Sergey, sorry I missed this entirely! Please let me know if it works ok for you now.

**Comment by naumenko-sa** [comment]
Thanks so much, Rachel @raerose01 !

I've updated the bioconda recipe and it now gives you 1.9.0.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-deconstructsigs/meta.yaml

Sergey
