### ISSUE TITLE
Save plots to a file

### ISSUE THREAD

**Issue by patidarr** [raerose01/deconstructSigs#8]
Hi,

Could you please add a parameter to save the plots to a file?
I tired 
pdf("mutationSignature2.pdf")
plotSignatures(sample_1, sub="ex")
makePie(sample_1,sub="ex")
dev.off()
would it be possible to add argument to send plots to a pdf/png files?

Thanks,
Rajesh

**Comment by raerose01** [comment]
Hi Rajesh,

Did you get an error when you tried to save plots that way? I have just used the same code to save the two plots.

Best,

Rachel

**Comment by patidarr** [comment]
Ahh my mistake, somehow eventhough I have dev.off the adobe is saying is either file is corrupted or open in another program. once I moved the file to another location it worked.

Thansk,
Rajesh
