### ISSUE TITLE
change the colors of the plotSignatures function

### ISSUE THREAD

**Issue by alexvat** [raerose01/deconstructSigs#9]
Can you change the colors to the usual ones used in cosmic? 
thanks in advance

**Comment by raerose01** [comment]
Hi, we are using the colors as used in previous publications from our lab. We currently aren't planning to make color choice a parameter, but you could alter the colors yourself by changing lines 70 (for the plot) and 95 (for the key) from the "plotSignatures" function found here:

https://github.com/raerose01/deconstructSigs/blob/master/R/plotting.R

**Comment by alexvat** [comment]
yes, thanks. I had already found it how to change them manually. I just thought for the user it is much easier if you provide them as an argument. 
Thanks
